integer V0; // chip.picosocInst_cpu.alu_out_q_reg 
integer V1; // chip.picosocInst_cpu.count_cycle_reg 
integer V2; // chip.picosocInst_cpu.count_instr_reg 
integer V3; // chip.picosocInst_cpu.cpu_state_reg 
integer V4; // chip.picosocInst_cpu.cpuregs.regs_reg_0 
integer V5; // chip.picosocInst_cpu.cpuregs.regs_reg_10 
integer V6; // chip.picosocInst_cpu.cpuregs.regs_reg_11 
integer V7; // chip.picosocInst_cpu.cpuregs.regs_reg_12 
integer V8; // chip.picosocInst_cpu.cpuregs.regs_reg_13 
integer V9; // chip.picosocInst_cpu.cpuregs.regs_reg_14 
integer V10; // chip.picosocInst_cpu.cpuregs.regs_reg_15 
integer V11; // chip.picosocInst_cpu.cpuregs.regs_reg_16 
integer V12; // chip.picosocInst_cpu.cpuregs.regs_reg_17 
integer V13; // chip.picosocInst_cpu.cpuregs.regs_reg_18 
integer V14; // chip.picosocInst_cpu.cpuregs.regs_reg_19 
integer V15; // chip.picosocInst_cpu.cpuregs.regs_reg_1 
integer V16; // chip.picosocInst_cpu.cpuregs.regs_reg_20 
integer V17; // chip.picosocInst_cpu.cpuregs.regs_reg_21 
integer V18; // chip.picosocInst_cpu.cpuregs.regs_reg_22 
integer V19; // chip.picosocInst_cpu.cpuregs.regs_reg_23 
integer V20; // chip.picosocInst_cpu.cpuregs.regs_reg_24 
integer V21; // chip.picosocInst_cpu.cpuregs.regs_reg_25 
integer V22; // chip.picosocInst_cpu.cpuregs.regs_reg_26 
integer V23; // chip.picosocInst_cpu.cpuregs.regs_reg_27 
integer V24; // chip.picosocInst_cpu.cpuregs.regs_reg_28 
integer V25; // chip.picosocInst_cpu.cpuregs.regs_reg_29 
integer V26; // chip.picosocInst_cpu.cpuregs.regs_reg_2 
integer V27; // chip.picosocInst_cpu.cpuregs.regs_reg_30 
integer V28; // chip.picosocInst_cpu.cpuregs.regs_reg_31 
integer V29; // chip.picosocInst_cpu.cpuregs.regs_reg_3 
integer V30; // chip.picosocInst_cpu.cpuregs.regs_reg_4 
integer V31; // chip.picosocInst_cpu.cpuregs.regs_reg_5 
integer V32; // chip.picosocInst_cpu.cpuregs.regs_reg_6 
integer V33; // chip.picosocInst_cpu.cpuregs.regs_reg_7 
integer V34; // chip.picosocInst_cpu.cpuregs.regs_reg_8 
integer V35; // chip.picosocInst_cpu.cpuregs.regs_reg_9 
integer V36; // chip.picosocInst_cpu.decoded_imm_j_reg 
integer V37; // chip.picosocInst_cpu.decoded_imm_reg 
integer V38; // chip.picosocInst_cpu.decoded_rd_reg 
integer V39; // chip.picosocInst_cpu.decoded_rs1_reg 
integer V40; // chip.picosocInst_cpu.decoded_rs2_reg 
integer V41; // chip.picosocInst_cpu.irq_mask_reg 
integer V42; // chip.picosocInst_cpu.irq_pending_reg 
integer V43; // chip.picosocInst_cpu.irq_state_reg 
integer V44; // chip.picosocInst_cpu.latched_rd_reg 
integer V45; // chip.picosocInst_cpu.mem_16bit_buffer_reg 
integer V46; // chip.picosocInst_cpu.mem_addr_reg 
integer V47; // chip.picosocInst_cpu.mem_rdata_q_reg 
integer V48; // chip.picosocInst_cpu.mem_state_reg 
integer V49; // chip.picosocInst_cpu.mem_wdata_reg 
integer V50; // chip.picosocInst_cpu.mem_wordsize_reg 
integer V51; // chip.picosocInst_cpu.mem_wstrb_reg 
integer V52; // chip.picosocInst_cpu.pcpi_div_dividend_reg 
integer V53; // chip.picosocInst_cpu.pcpi_div_divisor_reg 
integer V54; // chip.picosocInst_cpu.pcpi_div_pcpi_rd_reg 
integer V55; // chip.picosocInst_cpu.pcpi_div_quotient_msk_reg 
integer V56; // chip.picosocInst_cpu.pcpi_div_quotient_reg 
integer V57; // chip.picosocInst_cpu.pcpi_insn_reg 
integer V58; // chip.picosocInst_cpu.pcpi_mul_mul_counter_reg 
integer V59; // chip.picosocInst_cpu.pcpi_mul_pcpi_rd_reg 
integer V60; // chip.picosocInst_cpu.pcpi_mul_rd_reg 
integer V61; // chip.picosocInst_cpu.pcpi_mul_rdx_reg 
integer V62; // chip.picosocInst_cpu.pcpi_mul_rs1_reg 
integer V63; // chip.picosocInst_cpu.pcpi_mul_rs2_reg 
integer V64; // chip.picosocInst_cpu.pcpi_timeout_counter_reg 
integer V65; // chip.picosocInst_cpu.reg_next_pc_reg 
integer V66; // chip.picosocInst_cpu.reg_op1_reg 
integer V67; // chip.picosocInst_cpu.reg_op2_reg 
integer V68; // chip.picosocInst_cpu.reg_out_reg 
integer V69; // chip.picosocInst_cpu.reg_pc_reg 
integer V70; // chip.picosocInst_cpu.reg_sh_reg 
integer V71; // chip.picosocInst_cpu.timer_reg 
integer V72; // chip.picosocInst_cpu.pcpi_div_pcpi_wr_reg 
integer V73; // chip.picosocInst_cpu.pcpi_div_pcpi_ready_reg 
integer V74; // chip.picosocInst_cpu.pcpi_div_running_reg 
integer V75; // chip.picosocInst_cpu.decoder_trigger_reg 
integer V76; // chip.picosocInst_cpu.decoder_pseudo_trigger_reg 
integer V77; // chip.picosocInst_cpu.instr_setq_reg 
integer V78; // chip.picosocInst_cpu.instr_getq_reg 
integer V79; // chip.picosocInst_cpu.is_lb_lh_lw_lbu_lhu_reg 
integer V80; // chip.picosocInst_cpu.irq_active_reg 
integer V81; // chip.picosocInst_cpu.trap_reg 
integer V82; // chip.picosocInst_cpu.is_lbu_lhu_lw_reg 
integer V83; // chip.picosocInst_cpu.is_sb_sh_sw_reg 
integer V84; // chip.picosocInst_cpu.instr_retirq_reg 
integer V85; // chip.picosocInst_cpu.is_alu_reg_reg_reg 
integer V86; // chip.picosocInst_cpu.instr_lui_reg 
integer V87; // chip.picosocInst_cpu.is_alu_reg_imm_reg 
integer V88; // chip.picosocInst_cpu.is_slti_blt_slt_reg 
integer V89; // chip.picosocInst_cpu.is_compare_reg 
integer V90; // chip.picosocInst_cpu.is_sltiu_bltu_sltu_reg 
integer V91; // chip.picosocInst_cpu.is_lui_auipc_jal_reg 
integer V92; // chip.picosocInst_cpu.last_mem_valid_reg 
integer V93; // chip.picosocInst_cpu.pcpi_valid_reg 
integer V94; // chip.picosocInst_cpu.pcpi_mul_mul_finish_reg 
integer V95; // chip.picosocInst_cpu.pcpi_timeout_reg 
integer V96; // chip.picosocInst_cpu.do_waitirq_reg 
integer V97; // chip.picosocInst_cpu.irq_delay_reg 
integer V98; // chip.picosocInst_cpu.clear_prefetched_high_word_q_reg 
integer V99; // chip.picosocInst_cpu.latched_compr_reg 
integer V100; // chip.picosocInst_cpu.latched_is_lb_reg 
integer V101; // chip.picosocInst_cpu.latched_is_lh_reg 
integer V102; // chip.picosocInst_cpu.latched_is_lu_reg 
integer V103; // chip.picosocInst_cpu.pcpi_div_instr_remu_reg 
integer V104; // chip.picosocInst_cpu.pcpi_div_pcpi_wait_reg 
integer V105; // chip.picosocInst_cpu.pcpi_div_pcpi_wait_q_reg 
integer V106; // chip.picosocInst_cpu.mem_do_wdata_reg 
integer V107; // chip.picosocInst_cpu.mem_do_rdata_reg 
integer V108; // chip.picosocInst_cpu.mem_do_rinst_reg 
integer V109; // chip.picosocInst_cpu.mem_do_prefetch_reg 
integer V110; // chip.picosocInst_cpu.mem_instr_reg 
integer V111; // chip.picosocInst_cpu.mem_valid_reg 
integer V112; // chip.picosocInst_cpu.pcpi_mul_instr_mul_reg 
integer V113; // chip.picosocInst_cpu.pcpi_mul_instr_mulhu_reg 
integer V114; // chip.picosocInst_cpu.pcpi_mul_instr_mulhsu_reg 
integer V115; // chip.picosocInst_cpu.pcpi_mul_instr_mulh_reg 
integer V116; // chip.picosocInst_cpu.pcpi_mul_pcpi_wait_reg 
integer V117; // chip.picosocInst_cpu.pcpi_mul_pcpi_wait_q_reg 
integer V118; // chip.picosocInst_cpu.pcpi_mul_pcpi_ready_reg 
integer V119; // chip.picosocInst_cpu.pcpi_mul_pcpi_wr_reg 
integer V120; // chip.picosocInst_cpu.pcpi_div_instr_rem_reg 
integer V121; // chip.picosocInst_cpu.pcpi_div_instr_div_reg 
integer V122; // chip.picosocInst_cpu.pcpi_div_instr_divu_reg 
integer V123; // chip.picosocInst_cpu.pcpi_div_outsign_reg 
integer V124; // chip.picosocInst_cpu.prefetched_high_word_reg 
integer V125; // chip.picosocInst_cpu.pcpi_mul_mul_waiting_reg 
integer V126; // chip.picosocInst_cpu.latched_store_reg 
integer V127; // chip.picosocInst_cpu.instr_lhu_reg 
integer V128; // chip.picosocInst_cpu.instr_lh_reg 
integer V129; // chip.picosocInst_cpu.instr_lbu_reg 
integer V130; // chip.picosocInst_cpu.instr_lw_reg 
integer V131; // chip.picosocInst_cpu.instr_lb_reg 
integer V132; // chip.picosocInst_cpu.instr_sb_reg 
integer V133; // chip.picosocInst_cpu.instr_sh_reg 
integer V134; // chip.picosocInst_cpu.instr_sw_reg 
integer V135; // chip.picosocInst_cpu.instr_beq_reg 
integer V136; // chip.picosocInst_cpu.instr_bne_reg 
integer V137; // chip.picosocInst_cpu.instr_blt_reg 
integer V138; // chip.picosocInst_cpu.instr_bge_reg 
integer V139; // chip.picosocInst_cpu.instr_bltu_reg 
integer V140; // chip.picosocInst_cpu.instr_bgeu_reg 
integer V141; // chip.picosocInst_cpu.instr_rdcycleh_reg 
integer V142; // chip.picosocInst_cpu.instr_rdinstrh_reg 
integer V143; // chip.picosocInst_cpu.instr_timer_reg 
integer V144; // chip.picosocInst_cpu.instr_rdcycle_reg 
integer V145; // chip.picosocInst_cpu.instr_rdinstr_reg 
integer V146; // chip.picosocInst_cpu.instr_maskirq_reg 
integer V147; // chip.picosocInst_cpu.instr_ecall_ebreak_reg 
integer V148; // chip.picosocInst_cpu.instr_sll_reg 
integer V149; // chip.picosocInst_cpu.instr_srl_reg 
integer V150; // chip.picosocInst_cpu.instr_sra_reg 
integer V151; // chip.picosocInst_cpu.instr_sub_reg 
integer V152; // chip.picosocInst_cpu.instr_add_reg 
integer V153; // chip.picosocInst_cpu.instr_xor_reg 
integer V154; // chip.picosocInst_cpu.instr_slt_reg 
integer V155; // chip.picosocInst_cpu.instr_sltu_reg 
integer V156; // chip.picosocInst_cpu.instr_or_reg 
integer V157; // chip.picosocInst_cpu.instr_and_reg 
integer V158; // chip.picosocInst_cpu.instr_addi_reg 
integer V159; // chip.picosocInst_cpu.instr_xori_reg 
integer V160; // chip.picosocInst_cpu.instr_slli_reg 
integer V161; // chip.picosocInst_cpu.instr_srli_reg 
integer V162; // chip.picosocInst_cpu.instr_srai_reg 
integer V163; // chip.picosocInst_cpu.is_slli_srli_srai_reg 
integer V164; // chip.picosocInst_cpu.instr_slti_reg 
integer V165; // chip.picosocInst_cpu.instr_sltiu_reg 
integer V166; // chip.picosocInst_cpu.instr_ori_reg 
integer V167; // chip.picosocInst_cpu.instr_andi_reg 
integer V168; // chip.picosocInst_cpu.is_jalr_addi_slti_sltiu_xori_ori_andi_reg 
integer V169; // chip.picosocInst_cpu.mem_la_firstword_reg_reg 
integer V170; // chip.picosocInst_cpu.is_lui_auipc_jal_jalr_addi_add_sub_reg 
integer V171; // chip.picosocInst_cpu.instr_jal_reg 
integer V172; // chip.picosocInst_cpu.latched_stalu_reg 
integer V173; // chip.picosocInst_cpu.mem_la_secondword_reg 
integer V174; // chip.picosocInst_cpu.instr_waitirq_reg 
integer V175; // chip.picosocInst_cpu.compressed_instr_reg 
integer V176; // chip.picosocInst_cpu.instr_auipc_reg 
integer V177; // chip.picosocInst_cpu.instr_jalr_reg 
integer V178; // chip.picosocInst_cpu.is_beq_bne_blt_bge_bltu_bgeu_reg 
integer V179; // chip.picosocInst_cpu.latched_branch_reg 
