
`timescale 1ns / 1ps

`include "../../hdl/msp430core/omsp_alu.v"
`include "../../hdl/msp430core/omsp_and_gate.v"
`include "../../hdl/msp430core/omsp_clock_gate.v"
`include "../../hdl/msp430core/omsp_clock_module.v"
`include "../../hdl/msp430core/omsp_clock_mux.v"
`include "../../hdl/msp430core/omsp_dbg.v"
`include "../../hdl/msp430core/omsp_dbg_hwbrk.v"
`include "../../hdl/msp430core/omsp_dbg_i2c.v"
`include "../../hdl/msp430core/omsp_dbg_uart.v"
`include "../../hdl/msp430core/omsp_execution_unit.v"
`include "../../hdl/msp430core/omsp_frontend.v"
`include "../../hdl/msp430core/omsp_mem_backbone.v"
`include "../../hdl/msp430core/omsp_multiplier.v"
`include "../../hdl/msp430core/omsp_register_file.v"
`include "../../hdl/msp430core/omsp_scan_mux.v"
`include "../../hdl/msp430core/omsp_sfr.v"
`include "../../hdl/msp430core/omsp_sync_cell.v"
`include "../../hdl/msp430core/omsp_sync_reset.v"
`include "../../hdl/msp430core/omsp_wakeup_cell.v"
`include "../../hdl/msp430core/omsp_watchdog.v"
`include "../../hdl/msp430core/openMSP430.v"
`include "../../hdl/msp430core/openMSP430_defines.v"
`include "../../hdl/msp430core/openMSP430_undefines.v"
`include "../../hdl/msp430core/periph/omsp_gpio_16bit.v"
`include "../../hdl/msp430core/periph/omsp_uart.v"
`include "../../hdl/msp430core/periph/omsp_timerA.v"
`include "../../hdl/msp430core/periph/omsp_timerA_defines.v"
`include "../../hdl/msp430core/periph/omsp_timerA_undefines.v"
`include "../../hdl/msp430core/periph/customInv.v"
`include "../../hdl/msp430core/periph/customNand.v"
`include "../../hdl/msp430core/periph/rocell.v"
`include "../../hdl/msp430core/periph/ro_top_0.v"
`include "../../hdl/msp430core/periph/ro_top_1.v"
`include "../../hdl/msp430core/periph/ro_top_2.v"
`include "../../hdl/memory/sram_16_2k.v"
`include "../../hdl/memory/blk_mem_gen_v8_4.v"
`include "../../hdl/msp430core/single_core_msp430.v"


